### PR TITLE
specify newlines (\n) in other i18n

### PR DESCRIPTION
**Pull request by marocchino**
relate #237 and nodeschool/discussions-ja#3

### CODE REVIEW

**Comment by marocchino** [comment]
@isRuslan @dominhhai @martinheidegger @sugitach review please. :cat:

**Comment by isRuslan** [comment]
Oh, now I get, excuse me for misconfuse. Looks good for me then 👍

**Comment by marocchino** [comment]
:smile:

**Comment by dominhhai** [comment]
awesome! LGTM.

**Pull request merged**
