### PR TITLE
 Fixed grammatical errors (Russian)

### PR DESCRIPTION
**Pull request by demidborodin**

### CODE REVIEW

**Comment by demidborodin** [comment]
Anybody here? c:

**Comment by AnshulMalik** [comment]
Yeah, but I think we don't have anyone to review Russian

**Comment by AnshulMalik** [comment]
Awesome then, can you help us reviewing other Russian PRs which are in Russian? :)

**Comment by demidborodin** [comment]
@AnshulMalik sure. I will leave comments in the PR where I will agree with the changes or make additional changes.

**Pull request merged**
