### PR TITLE
Change `var` by `let` and `const` for HTTP_COLLECT

### PR DESCRIPTION
**Pull request by jmpp**
As requested in #559 , here's my contribution for "ES6sify" exercice :)

### CODE REVIEW

**Comment by AnshulMalik** [comment]
Hey @jmpp That's great. It's be awesome to see [exercise.js](https://github.com/jmpp/learnyounode/blob/7eb78bfd74413f1297de8283656dd1ceb53b94ce/exercises/http_collect/exercise.js) to be using const as well :)

**Comment by jmpp** [comment]
That's right. I totally forgotten that the exercice file count too. I did the update and squashed my changes.

This PR seems to be up to date, on the other hand, I don't understand why Travis build failed :/

**Comment by AnshulMalik** [comment]
https://travis-ci.org/workshopper/learnyounode/jobs/291454046

Tge variable `standard` changes over time, so defining it as const is
causing issues.

**Comment by jmpp** [comment]
I see. So do I have anything to do to fix this ?

**Comment by AnshulMalik** [comment]
Simplest solution is to define it using `let` instead of `const`.
And another would be to use good names of reassigned variables.

**Comment by jmpp** [comment]
@AnshulMalik Fixed then. I ran the tests locally and it seems to work now :)

**Comment by jmpp** [comment]
@AnshulMalik Finally done :)

**Comment by AnshulMalik** [comment]
Thanks @jmpp

**Pull request merged**
