### PR TITLE
Added Ukrainian translation.

### PR DESCRIPTION
**Pull request by denysdovhan**
I've translated _learnyounode_ on Ukrainian. Please, add my languages.

image

### CODE REVIEW

**Comment by tgfjt** [comment]
Great! Thank you.:)
Are there anyone can review this?

**Comment by denysdovhan** [comment]
> Are there anyone can review this?

@tgfjt anyone who know Ukrainian:) For example, @sudodoki (founder of [nodeschool/kyiv](https://github.com/nodeschool/kyiv)) or @terry-s could do this.

**Comment by terry-s** [comment]
I'll review this :)

**Comment by sudodoki** [comment]
I'll take a look as well. cc @nodeschool/kyiv

**Comment by denysdovhan** [comment]
@tarry-s has made review and fixed mistakes. So, @tgfjt, you can merge it.

**Comment by terry-s** [comment]
Everything is good, I've fixed some mistakes. @tgfjt, I think you can merge it.

**Comment by tgfjt** [comment]
@denysdovhan
@sudodoki
@terry-s
Thank you all!!

**Comment by rilian** [comment]
:+1:

**Comment by denysdovhan** [comment]
I will translate other workshops, if I'll have free time. So, wait for my new commits, guys! :smirk_cat:

**Pull request merged**
