### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by mahaker**

### CODE REVIEW

**Comment by AnshulMalik** [comment]
Hey @mahaker, I don't know Japanese, could you help me with this change? Don't know any reviewer.

**Comment by mahaker** [comment]
Hi @AnshulMalik .
Thank you for the comment!

The problem is second `に` .
The word is not continuous.

**Comment by mahaker** [comment]
Is this enough?

**Comment by martinheidegger** [comment]
Lgtm!

**Comment by AnshulMalik** [comment]
Wanted to do a rebase, can't push here. Would you please do it for me? @mahaker

**Comment by mahaker** [comment]
ok!!

**Pull request merged**
