### PR TITLE
WLjJsJa add WLjJsJa_baby_steps.js

### PR DESCRIPTION
**Pull request by cesargafer**
add baby_steps WLjJsJa style!! :octocat:

### CODE REVIEW

**Comment by jpwesselink** [comment]
Hi @cesargafer, can you explain a little what you are trying to achieve?

**Comment by cesargafer** [comment]
Hi @jpwesselink, it`s part of an assignment of olinjs. :bowtie:
olinjs/lessons/01-welcome-internet/HOMEWORK.md

Is there some issue? plz suggest & advice

**Comment by martinheidegger** [comment]
@cesargafer Congratulations on working out learnyounode. I hope you like the lesson. However you made a PR, a [Pull Request](https://help.github.com/articles/about-pull-requests/). The purpose of a Pull Request is to tell us that you have something that can improve Learnyounode. _(I was not able to find any reference in `onlijs` that makes this part of the lecture)_ From what you are committing it seems like you just work the exercises. Am I right? Or do you want to commit this as suggest for us to do something with it?

**Comment by martinheidegger** [comment]
I have closed this PR. I hope its alright with you @cesargafer

**Pull request closed without merging**
