### PR TITLE
Change : var to let/const in exercise.js

### PR DESCRIPTION
**Pull request by gagandeepp**
Changed var to let/const in exercise.js file for baby_steps problem

### CODE REVIEW

**Comment by gagandeepp** [comment]
@AnshulMalik  Please review this PR and consider this as my contribution to oktoberfest 2018

**Comment by AnshulMalik** [comment]
Looks like you need to rebase.

**Comment by AnshulMalik** [comment]
I am seeing a lot of commits, looks like you made changes on top of some strange commit.

**Comment by srl295** [comment]
see also #662

**Comment by AnshulMalik** [comment]
Closing due to inactivity.

**Pull request closed without merging**
