### PR TITLE
Norwegian translation

### PR DESCRIPTION
**Pull request by leftieFriele**
This is a join effort by the team in https://github.com/orgs/nodeschool-no/people. We've [reviewed each others contributions](https://github.com/nodeschool-no/oversettere/milestones/Learnyounode%20oversettelse) so there shouldn't be a big need for second opinions :)

The translation is done by @phillipj, @torsph and me

### CODE REVIEW

**Comment by leftieFriele** [comment]
I just remembered, that in order for this workshop to be completely Norwegian the project needs to run workshopper@2.6.0 which has the new Norwegian translation for workshopper

**Comment by marocchino** [comment]
@leftieFriele Thank you for your works. Is this reviewed?

**Comment by Torsph** [comment]
@marocchino Me, @leftieFriele and @phillipj have translated and reviewed the text.

**Comment by marocchino** [comment]
:+1:

**Comment by marocchino** [comment]
Update warkshopper version in #311

**Comment by leftieFriele** [comment]
I see that we forgot to add @Torsph and @phillipj as contributors, I don't know if that's customary to do or not.

**Pull request merged**
