### PR TITLE
Add browser guide

### PR DESCRIPTION
**Pull request by finnp**
Hey,

I created a module called [workshopper-browser-guide](https://github.com/finnp/workshopper-browser-guide) for creating git-it-style html guides from the exercises.

This PR adds this module and a few scripts for creating the html versions as well as publishing it to GitHub pages. This means that for every exercise change, you will need to run:  `npm run guide`

I published an example for this over here: http://www.finnpauls.de/learnyounode/guide/

What do you think?

Best,
Finn

### CODE REVIEW

**Comment by julianduque** [comment]
I love the final result <3 but not exactly sure about the `publishguide` script, lets see what other collaborators think about it

**Comment by finnp** [comment]
@julianduque Yeah, I am also not sure about that part. Maybe there's a better way to do this, so I am open for input.

**Comment by rvagg** [comment]
OK, I'm kind of +0 on this because I don't entirely see the utility. Can you explain the workflow and how it would be useful to end-users?

Also, I have the domain node.institute so we could do **learnyou.node.institute** or something equally ridiculous. learnyounode.nodeschool.io is possible too, but a tiny bit boring.

**Comment by julianduque** [comment]
@rvagg I'm +1 to publish the guide under that domain but not sure as I said to add it to the project

**Comment by sidorares** [comment]
GUI workshopper using atom-shell :)

**Comment by finnp** [comment]
The reason why I though it should be included in the learnyounode workshoper was that I noticed that many people have troubles in the beginning because they don't remember the exercises correctly. Or because they didn't read them completely, since their terminal cuts of parts of the exercise. I think if students have the ability to look at the exercises in a different window on a browser, it's easier for them.

To make this accessible I suggest adding a menu item with a link to the guide or mentioning the guide in the exercise footers.

**Comment by julianduque** [comment]
@finnp something like this to the end of the problem:

To see this guide online check http://www.finnpauls.de/learnyounode/guide/hello_world.html

**Comment by finnp** [comment]
@julianduque That would be fine with me. The reason why I did it as part fo the workshopper was the Offline-first mentality of NodeSchool. Linking an external guide is not accessible without internet.

**Comment by finnp** [comment]
@rvagg I like http://learnyou.node.institute. Maybe you could setup a CNAME for the gh-pages branch?

**Comment by rvagg** [comment]
done, and populated with some initial awesome

**Pull request closed without merging**
