### PR TITLE
explicit check for '.' prefix usage

### PR DESCRIPTION
**Pull request by rvagg**
Potential fix for #222 & nodeschool/discussions#64 & countless other confused issues filed about the _"did not return an Array with the correct number of elements as the second argument of the callback"_ error when all they are doing wrong is passing in the extension with a `.` prefixed when they were asked not to.

Failure looks like this:

screenshot from 2015-02-16 16 04 23

Collaborators, if I could have your help to review this, at least:

* Comment on the wording I've used here if you have suggestions for improvements
* Start translating the new strings!

Also included some minor style fixes for stuff I keep stumbling across that crept in with the i18n changes.

### CODE REVIEW

**Comment by martinheidegger** [comment]
It seems to me that even more than the last problem: `Submission results match expected` seems to confuse people.

Maybe we should add a `[1 of 8] ✔︎ Submission results match expected` or so.

Perhaps a wording there would help too `[1 of 8] ✔︎ Submission output is as expected`

**Comment by rvagg** [comment]
* Re "Submission results match expected" - this is accurate, and IMO reasonable, you can get correct output even if you've implemented it wrong. The exercise explicitly asks you to implement to an API contract, so that's why we go further and do all the "Additional module file ...." stuff which validates _on top_ of checking output. My interpretation of the problems people face with this exercise is simply that the "Array with the correct number of elements" thing doesn't help in any way, it doesn't point them towards a fix for the problem and can even make people believe it's a bug on our end. _However_, I've not been as active in nodeschool/discussions as I used to be so perhaps you're picking up on something different?
* Counting the number of ticks/crosses ahead of time is problematic, at the moment they are defined really loose so workshopper can't know ahead of time what it's going to get.
  - We could queue up the pass/fail events and print them out at the end which would give us more control over how they are presented--I ran into this problem today when I was adding the JSON stringify guard in #226, I'd like to print a tick/cross with that bit but the mess I had to code to make it workable made it unjustifiable so I wound back and just added in the try/catch without any prints. This is because that's all done _while_ things are being printed to stdout for comparison so you end up getting ticks and crosses in between the stdout comparison print (there's additional problems on top of that ...). Basically, it's not ideal the way it is now.
  - We could overhaul the `'pass'` and `'fail'` thing to make it more interesting and rigorous, more like a test runner where there are a set of pre-defined asserts you must pass, all with fixed messages, and you either get a tick or a cross next to each one. At the moment they are just events that print stuff and have no impact on anything else (actual pass/fail is controlled by something else entirely).

**Comment by jkbits1** [comment]
I think the new error message is a big improvement. It gives the student clear guidance on where the error might be, and how it might be fixed. This could remove a lot of frustration that students feel at present when the output is right, but they keep failing for an unclear reason.

At the moment, it is quite hard to put give the student a hint, without actually giving them the entire answer. This removes some of the fun for both student (and helpers) - for problem-solvers it's always feels better when they are able to put the last bit of puzzle in place themselves.

**Comment by rvagg** [comment]
@julianduque
@martinheidegger
@ClimbsRocks
@tgfjt
@AtuyL
@lisposter
@haradats
@a0viedo
@lucasfcosta
@ericdouglas
@leonascimento
@isRuslan
@tdd
@gorhgorh

i18n folks, this is published as v2.6.0 but on the `next` tag rather than `latest` so you won't get it unless you explicitly ask for it (`npm install learnyounode@2.6.0 -g` or `npm install learnyounode@next -g`). The reason being that this contains new un-translated text.

PR to the **next** branch and add `fail.mod.dont_use_dot` and `pass.mod.dont_use_dot` as per the additions in en.json and we can get this properly published on `latest`. Thanks!

**Comment by rjmunro** [comment]
It looks like this issue is addressed in #227.

**Pull request merged**
