### PR TITLE
A rephrasing of the similarity to `wc -l`

### PR DESCRIPTION
**Pull request by joshhartigan**
As requested in https://github.com/nodeschool/discussions/issues/620

### CODE REVIEW

**Comment by martinheidegger** [comment]
TRANSLATION! :fist:

**Comment by martinheidegger** [comment]
I am wondering how to deal with translation of this. @a0viedo @tdd any thoughts?

**Comment by tdd** [comment]
Oh woah, this is old. Hadn't seen this. Do you mean: how to ping translators? It seems you need to at-mention all the main L10n committers, then get as many PR's… Not sure what the best workflow would be for this, but hey!

**Comment by tdd** [comment]
Hey, sorry about the misfire on my previous commit, hadn't updated `l10n-fr` and was looking at master, not `next`. #271 translates the rewording from this as a PR onto `next`.

**Comment by a0viedo** [comment]
we don't have localization teams (yet?), we could make a list in a markdown file for the people involved in each language

**Comment by SomeoneWeird** [comment]
Just reading through issues and chiming in, we could add translation teams so we can just ping @translation/jp etc. when need be. It might also be worth adding some tags for 'translation needed' etc.

**Comment by martinheidegger** [comment]
It was my mistake to try to start a general discussion here ;) We should continue that another place.  Aside from that: There seems to be a conflict which doesn't allow me to automatically merge the PR @joshhartigan do you mind to update the PR?

**Comment by AnshulMalik** [comment]
Closing due to inactivity.

**Pull request closed without merging**
