### PR TITLE
Fix mistakes in russian translation

### PR DESCRIPTION
**Pull request by eveness**

### CODE REVIEW

**Comment by martinheidegger** [comment]
@eveness Thank you for the PR. Since I don't speak russian it would be nice if you could describe the problem that you fixed.

**Comment by eveness** [comment]
I`ll try explain (since I don't speak english well), there were two grammatical errors and one forgotten comma.

**Comment by martinheidegger** [comment]
It is okay if the description is in russian (for the future). In case some russian person check-reads it.

**Comment by martinheidegger** [comment]
Its published as 3.5.6

**Comment by marinintim** [comment]
As a native Russian speaker, I approve these changes. In fact we at @nodeschool/spb were thinking about proofreading entire translation, because it was done under severe deadlines and kind of messy.

**Pull request merged**
