### PR TITLE
Randomize sever delay in range (1-500 ms).

### PR DESCRIPTION
**Pull request by kishorsharma**
Randomize server delay time in range (1-500 ms ) in ref. to issue: https://github.com/workshopper/learnyounode/issues/284

### CODE REVIEW

**Comment by martinheidegger** [comment]
Right now the range is not distributed: The reason why the random time before this PR had 3 distinct durations is to make sure that the test can deal with either. If you want to randomize it it would be good to have something like:

```JavaScript
var times = [];
times.push(Math.random() * 100 + 1)
times.push(times[0] + 100 + Math.random() * 100)
times.push(times[1] + 100 + Math.random() * 100) 
times = times.shuffle()
```

**Comment by martinheidegger** [comment]
@kishorsharma Do you agree? Should I close this issue?

**Comment by kishorsharma** [comment]
@martinheidegger yes I totally agree with you. I am sorry for late (actually not) replying, As I was thinking to use  [this shuffle](http://stackoverflow.com/a/6274398) for the same.  If it ok I can update my pr.

**Comment by martinheidegger** [comment]
@kishorsharma Sure, looking forward to it!

**Comment by kishorsharma** [comment]
@martinheidegger I have made changes.. :)

**Comment by martinheidegger** [comment]
Thank you! Looks awesome.

**Comment by martinheidegger** [comment]
Note: `let` keyword is not yet okay. Changed it to `var` and published as 3.4.1

**Pull request merged**
