### PR TITLE
updated baby_steps exercise to use const or let instead of var

### PR DESCRIPTION
**Pull request by martiuslim**
Referencing #559

Please let me know if this is the preferred way of submitting updates for the exercises (1 pr per exercise as requested) and I'll send in more prs when ready :smile:

### CODE REVIEW

**Comment by AnshulMalik** [comment]
Looks like you upset the standard gods :O

**Comment by martiuslim** [comment]
Did I do something wrong?

**Comment by AnshulMalik** [comment]
Nah, it's a simple error, run `standard` or `npm run standard`, you'll know.
It's the `exercise` variable which is not constant, it changes.

**Comment by martiuslim** [comment]
Oh right! Sorry haha didn't realise that. I have updated the code :smile:

**Pull request merged**
