### PR TITLE
Update problems to use const and let

### LINKED ISSUE #660: Update problems to use const and let
Hi, I like learnyounode. This workshop helped me to learn Node.js.
However, this workshop is a little outdated.
This is the proposal to replace var to let/const in problem.md like solution (PR: https://github.com/workshopper/learnyounode/issues/555).
The below list indicates problem.md including 'var'.

- [ ] http_collect
- [ ] http_file_server
- [ ] http_uppercaserer
- [ ] make_it_modular
- [ ] my_first_io
- [ ] time_server

### PR DESCRIPTION
**Pull request by shisama**
resolve #660 

'var' is used in some problem.md files. I think 'let' or 'const' should be used instead of 'var'.

### CODE REVIEW

**Comment by shisama** [comment]
Is there anybody who can review this?

**Comment by shisama** [comment]
@AnshulMalik Hi, I created this PR 5 months ago. Please review this PR and merge it when you have time. Thanks.

**Comment by AnshulMalik** [comment]
Hi @shisama, sorry it went unnoticed for so long. Probably because of so many file changes together. I am so sorry for not having a look at it.
I think the exercises are already converted by community.

**Comment by shisama** [comment]
@AnshulMalik Thank you for your reply. 

> Probably because of so many file changes together.

Is it better for you to divide this PR each exercise? For example, one is PR to convert [exercises/http_collect](https://github.com/workshopper/learnyounode/tree/master/exercises/http_collect), two is [exercises/http_file_server](https://github.com/workshopper/learnyounode/tree/master/exercises/http_file_server), ...

> I think the exercises are already converted by community.

OK, I will change the latest code again.

**Comment by AnshulMalik** [comment]
Yes @shisama one PR per exercise is generally best. Moreover not many exercises are left now :)

**Pull request closed without merging**
