### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by claudiopro**
Hey @martinheidegger I prepared an Italian translation for `learnyounode` :smile:

### CODE REVIEW

**Comment by martinheidegger** [comment]
Looks good! We usually ask if there is someone to review it for you, have you someone?

**Comment by claudiopro** [comment]
I can surely find someone from the Italian NodeSchool chapter. Let me give them a shout!

**Comment by claudiopro** [comment]
For the reviewer, do the following:

Step 1: clone the `learnyounode` repo 
```
git clone git@github.com:workshopper/learnyounode.git
cd learnyounode
```
Step 2: add my fork as a remote
```
git remote add claudiopro git@github.com:claudiopro/learnyounode.git
```
Step 3: create a branch and pull the branch
```
git checkout -b test-italian-translation
git pull claudiopro italian-translation
```
Step 4: test the workshop
```
bin/learnyounode
```

**Comment by martinheidegger** [comment]
@claudiopro I added a step 4 before 5

**Comment by claudiopro** [comment]
Whoops :blush: thanks!

**Comment by lambrojos** [comment]
Hi guys I am officially volunteering for this review, I think @claudiopro step by step guide is clear enough for getting started. What should I do in the case I find something that needs correction? Open an issue on the forked repo?

**Comment by claudiopro** [comment]
Hi @lambrojos I think it's fine to comment here and I'll fix unless Martin disagrees?

**Comment by martinheidegger** [comment]
@claudiopro @lambrojos It is up to you to decide how you communicate. I heard Gitter is nice :) . Maybe it depends on the amount: If is much that needs changing it might be fastest for @lambrojos to fork https://github.com/claudiopro/learnyounode/tree/italian-translation and create a PR towards it and let @claudiopro merge that by hand.

**Comment by claudiopro** [comment]
@martinheidegger hi Martin, @lambrojos reviewed the translation files. Want me to squash / rebase?

**Comment by martinheidegger** [comment]
Yes please :)

**Comment by martinheidegger** [comment]
Merged anyway. Btw. the credits title seems to be untranslated!

**Comment by claudiopro** [comment]
Hmm? Which resource/line?

**Comment by martinheidegger** [comment]
screenshot 2016-02-01 08 21 17
In the workshopper-adventure, the [italian version](https://github.com/workshopper/workshopper-adventure/blob/3e1950eb0bb66331bc0490606f2c63598ffcb57c/i18n/it.json) should also have the [credit keys](https://github.com/workshopper/workshopper-adventure/blob/3e1950eb0bb66331bc0490606f2c63598ffcb57c/i18n/en.json#L71)

**Comment by claudiopro** [comment]
そか！I'll fix this ASAP, thanks for spotting it :smile:

**Comment by kildem** [comment]
exercise one verify is broken!

    ?exercises.HELLO WORLD.compare.title || common.exercise.compare.title || compare.title?

    /usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/comparestdout.js:19
      return new Array(sz + 1).join(ch)
             ^

    RangeError: Invalid array length

**Pull request merged**
